# Server Configuration
server:
  port: 9000

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Logging Configuration
logging:
  level:
    web: DEBUG

spring:
  devtools:
    add-properties: true

  datasource:
    # OracleDB Connection Configuration
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: DB_ROOT_USR
    password: ORACLE
    driver-class-name: oracle.jdbc.OracleDriver

    # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPool

  # JPA settings
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
